(function(){
  const state=window.CanvasAgentState, $=id=>document.getElementById(id), panel=$('canvasAgentPanel');
  const status = value => { $('canvasAgentStatus').textContent=value || ''; };
  const message = (content, kind='agent') => { if (!content) return; const el=document.createElement('div'); el.className=`canvas-agent-message ${kind}`; el.textContent=content; $('canvasAgentMessages').appendChild(el); $('canvasAgentMessages').scrollTop=$('canvasAgentMessages').scrollHeight; };
  const system = content => message(content, 'system');
  const modelStorageKey = () => `canvas-agent-model:${window.CanvasAgentBridge.canvasId()}`;
  function modelSelection() { return {provider:state.modelProvider || '', model:state.modelName || ''}; }
  function saveModelSelection() { localStorage.setItem(modelStorageKey(), JSON.stringify(modelSelection())); }
  function loadModelSelection() { try { const saved=JSON.parse(localStorage.getItem(modelStorageKey()) || '{}'); state.modelProvider=String(saved.provider || ''); state.modelName=String(saved.model || ''); } catch (_) {} }
  async function loadModels() { const select=$('canvasAgentModelSelect'); try { const response=await fetch('/api/providers',{credentials:'same-origin'}); if(!response.ok) throw new Error(`请求失败 (${response.status})`); const data=await response.json(); const previous=modelSelection(); select.innerHTML=''; const automatic=document.createElement('option'); automatic.value=''; automatic.textContent='自动选择'; automatic.dataset.provider=''; automatic.dataset.model=''; select.appendChild(automatic); (data.providers||[]).filter(provider=>provider.enabled!==false).forEach(provider=>{ (provider.chat_models||[]).forEach(model=>{ const option=document.createElement('option'); option.value=`${provider.id}::${model}`; option.textContent=`${provider.name || provider.id} / ${model}`; option.dataset.provider=provider.id || ''; option.dataset.model=model; select.appendChild(option); }); }); const selected=[...select.options].find(option=>option.dataset.provider===previous.provider&&option.dataset.model===previous.model); select.value=selected ? selected.value : ''; if(!selected){state.modelProvider='';state.modelName='';} } catch (_) { select.innerHTML='<option value="">自动选择（模型列表加载失败）</option>'; } }
  function onModelChange(event) { const option=event.target.selectedOptions[0]; state.modelProvider=option?.dataset.provider || ''; state.modelName=option?.dataset.model || ''; saveModelSelection(); }
  const runLabel = run => { const title=String(run.title || '').trim().replace(/\s+/g,' '); const short=title ? (title.length > 34 ? `${title.slice(0,34)}…` : title) : '新建对话'; return `${short} · ${run.status || 'created'}`; };
  async function refreshRuns() {
    const select=$('canvasAgentRunSelect');
    let runs=[];
    try {
      const data=await window.CanvasAgentClient.listRuns(window.CanvasAgentBridge.canvasId());
      runs=data.runs||[];
    } catch (_) {}
    const known=new Set(runs.map(run=>run.id));
    try {
      const history=JSON.parse(localStorage.getItem(`canvas-agent-runs:${window.CanvasAgentBridge.canvasId()}`) || '[]');
      history.filter(id=>id && !known.has(id)).forEach(id=>runs.push({id,status:id===state.runId?'created':'unknown',title:'历史 Run'}));
    } catch (_) {}
    if(state.runId && !known.has(state.runId)) runs.unshift({id:state.runId,status:'created',title:'当前 Run'});
    select.innerHTML='';
    if(!runs.length){ const empty=document.createElement('option'); empty.value=''; empty.textContent='暂无 Run，点击 + 新建'; select.appendChild(empty); return; }
    runs.forEach(run=>{ const option=document.createElement('option'); option.value=run.id; option.textContent=runLabel(run); option.title=run.title || run.id; option.selected=run.id===state.runId; select.appendChild(option); });
  }
  function clearRun() { $('canvasAgentMessages').innerHTML=''; $('canvasAgentPlan').innerHTML=''; $('canvasAgentPlan').hidden=true; $('canvasAgentArtifacts').innerHTML=''; $('canvasAgentArtifacts').hidden=true; state.plan=null; state.tasks=[]; }
  function renderMentions() { const box=$('canvasAgentMentions'); box.innerHTML=''; state.mentions.forEach(id => { const chip=document.createElement('span'); chip.className='canvas-agent-mention'; chip.textContent=`@${window.CanvasAgentBridge.nodeLabel(id)}`; const remove=document.createElement('button'); remove.type='button'; remove.textContent='×'; remove.addEventListener('click',()=>{state.mentions=state.mentions.filter(item=>item!==id);renderMentions();}); chip.appendChild(remove); box.appendChild(chip); }); }
  function renderRun(data) { const run=data.run||{}; if (run.id) { state.runId=run.id; window.CanvasAgentEvents.saveRun(); } status(`${run.status || 'unknown'} · ${run.phase || ''}`); const messages=$('canvasAgentMessages'); messages.innerHTML=''; (data.messages||[]).forEach(item=>message(item.content,item.role==='user'?'user':item.role==='system'?'system':'agent')); state.sequence=Math.max(state.sequence,...(data.events||[]).map(event=>Number(event.sequence)||0)); window.CanvasAgentPlan.render(data.plan); window.CanvasAgentArtifacts.render(data.tasks||[], data.artifacts||[]); if((data.artifacts||[]).length)window.CanvasAgentArtifacts.renderDocChain(data.artifacts); if (run.status === 'completed') { const box=$('canvasAgentArtifacts'); box.hidden=false; const row=document.createElement('div'); row.className='canvas-agent-plan-actions'; [['通过','approved'],['需要修改','needs_revision']].forEach(([label,value])=>{const b=document.createElement('button');b.className='canvas-agent-action secondary';b.type='button';b.textContent=label;b.addEventListener('click',async()=>{try{renderRun(await window.CanvasAgentClient.review(value));}catch(e){system(e.message);}});row.appendChild(b);});box.appendChild(row); } }
  async function ensureRun() { if (state.runId) return state.runId; status('正在创建会话'); const data=await window.CanvasAgentClient.createRun(); state.runId=data.run.id; window.CanvasAgentEvents.saveRun(); await refreshRuns(); return state.runId; }
  async function newRun() { if (state.busy) return; state.busy=true; window.CanvasAgentEvents.stop(); state.runId=''; state.sequence=0; clearRun(); status('正在创建会话'); try { const data=await window.CanvasAgentClient.createRun(); state.runId=data.run.id; window.CanvasAgentEvents.saveRun(); renderRun({run:data.run,messages:[],events:[],tasks:[],artifacts:[]}); await refreshRuns(); } catch (e) { system(e.message); status('创建失败'); } finally { state.busy=false; } }
  async function send() { const input=$('canvasAgentInput'), content=input.value.trim(); if (!content || state.busy) return; state.busy=true; input.value=''; message(content,'user'); try { await ensureRun(); const selection=modelSelection(); const data=await window.CanvasAgentClient.send({content,provider:selection.provider,model:selection.model,selected_node_ids:window.CanvasAgentBridge.selectedNodeIds(),mention_node_ids:state.mentions}); renderRun(data); window.CanvasAgentEvents.start(); } catch(e) { system(e.message); status('error'); } finally { state.busy=false; } }
  async function answer(answer) { if (!answer?.trim() || !state.runId) return; try { const selection=modelSelection(); const data=await window.CanvasAgentClient.answer(answer.trim(),selection.provider,selection.model); if (data.plan) window.CanvasAgentPlan.render(data.plan); else status('已收到回答'); window.CanvasAgentEvents.start(); } catch(e) { system(e.message); } }
  async function confirm(approved) { if (!state.plan || !state.runId) return; try { const authorize=$('canvasAgentAuthorizeNodes')?.checked; const data=await window.CanvasAgentClient.request(`/api/canvas-agent/runs/${encodeURIComponent(state.runId)}/confirm`, {method:'POST', body:JSON.stringify({plan_version:state.plan.version,approved,authorized_node_ids:authorize ? state.mentions : []})}); renderRun(data); if (approved) window.CanvasAgentBridge.refreshCanvas(); window.CanvasAgentEvents.start(); } catch(e) { system(e.message); } }
  async function cancel() { if (!state.runId) return; try { renderRun(await window.CanvasAgentClient.cancel()); window.CanvasAgentEvents.stop(); } catch(e) { system(e.message); } }
  function addSelectedMentions() { const ids=window.CanvasAgentBridge.selectedNodeIds(); state.mentions=[...new Set([...state.mentions,...ids])]; renderMentions(); if (!ids.length) system('请先在画布上选中节点。'); }
  function init() { loadModelSelection(); $('canvasAgentToggle').addEventListener('click',()=>{panel.hidden=!panel.hidden;if(!panel.hidden){loadModels();refreshRuns();window.CanvasAgentEvents.recover();}}); ['pointerdown','mousedown','click','dblclick'].forEach(type=>panel.addEventListener(type,event=>event.stopPropagation())); $('canvasAgentClose').addEventListener('click',()=>panel.hidden=true); $('canvasAgentRunSelect').addEventListener('change',event=>window.CanvasAgentEvents.switchRun(event.target.value)); $('canvasAgentNewRun').addEventListener('click',newRun); $('canvasAgentModelSelect').addEventListener('change',onModelChange); $('canvasAgentSend').addEventListener('click',send); $('canvasAgentCancel').addEventListener('click',cancel); $('canvasAgentMention').addEventListener('click',addSelectedMentions); $('canvasAgentInput').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send();}}); window.addEventListener('beforeunload',window.CanvasAgentEvents.stop); renderMentions(); loadModels(); refreshRuns(); window.CanvasAgentEvents.recover(); }
  window.CanvasAgentPanel={init,status,message,system,renderRun,clearRun,refreshRuns,send,answer,confirm,cancel}; init();
})();
