(function(){
  const state=window.CanvasAgentState, $=id=>document.getElementById(id), panel=$('canvasAgentPanel');
  const status = value => { $('canvasAgentStatus').textContent=value || ''; };
  const message = (content, kind='agent') => { if (!content) return; const el=document.createElement('div'); el.className=`canvas-agent-message ${kind}`; el.textContent=content; $('canvasAgentMessages').appendChild(el); $('canvasAgentMessages').scrollTop=$('canvasAgentMessages').scrollHeight; };
  const system = content => message(content, 'system');
  const runLabel = run => { const title=String(run.title || '').trim().replace(/\s+/g,' '); const short=title ? (title.length > 34 ? `${title.slice(0,34)}…` : title) : '新建对话'; return `${short} · ${run.status || 'created'}`; };
  async function refreshRuns() { try { const data=await window.CanvasAgentClient.listRuns(window.CanvasAgentBridge.canvasId()); const select=$('canvasAgentRunSelect'); const runs=data.runs||[]; select.innerHTML=''; if(!runs.length){ const empty=document.createElement('option'); empty.value=''; empty.textContent='暂无 Run，点击 + 新建'; select.appendChild(empty); return; } runs.forEach(run=>{ const option=document.createElement('option'); option.value=run.id; option.textContent=runLabel(run); option.title=run.title || run.id; option.selected=run.id===state.runId; select.appendChild(option); }); if(state.runId && !runs.some(run=>run.id===state.runId)) select.value=''; } catch (_) {} }
  function clearRun() { $('canvasAgentMessages').innerHTML=''; $('canvasAgentPlan').innerHTML=''; $('canvasAgentPlan').hidden=true; $('canvasAgentArtifacts').innerHTML=''; $('canvasAgentArtifacts').hidden=true; state.plan=null; state.tasks=[]; }
  function renderMentions() { const box=$('canvasAgentMentions'); box.innerHTML=''; state.mentions.forEach(id => { const chip=document.createElement('span'); chip.className='canvas-agent-mention'; chip.textContent=`@${window.CanvasAgentBridge.nodeLabel(id)}`; const remove=document.createElement('button'); remove.type='button'; remove.textContent='×'; remove.addEventListener('click',()=>{state.mentions=state.mentions.filter(item=>item!==id);renderMentions();}); chip.appendChild(remove); box.appendChild(chip); }); }
  function renderRun(data) { const run=data.run||{}; if (run.id) { state.runId=run.id; window.CanvasAgentEvents.saveRun(); } status(`${run.status || 'unknown'} · ${run.phase || ''}`); const messages=$('canvasAgentMessages'); messages.innerHTML=''; (data.messages||[]).forEach(item=>message(item.content,item.role==='user'?'user':item.role==='system'?'system':'agent')); state.sequence=Math.max(state.sequence,...(data.events||[]).map(event=>Number(event.sequence)||0)); window.CanvasAgentPlan.render(data.plan); window.CanvasAgentArtifacts.render(data.tasks||[], data.artifacts||[]); if((data.artifacts||[]).length)window.CanvasAgentArtifacts.renderDocChain(data.artifacts); if (run.status === 'completed') { const box=$('canvasAgentArtifacts'); box.hidden=false; const row=document.createElement('div'); row.className='canvas-agent-plan-actions'; [['通过','approved'],['需要修改','needs_revision']].forEach(([label,value])=>{const b=document.createElement('button');b.className='canvas-agent-action secondary';b.type='button';b.textContent=label;b.addEventListener('click',async()=>{try{renderRun(await window.CanvasAgentClient.review(value));}catch(e){system(e.message);}});row.appendChild(b);});box.appendChild(row); } }
  async function ensureRun() { if (state.runId) return state.runId; status('正在创建会话'); const data=await window.CanvasAgentClient.createRun(); state.runId=data.run.id; window.CanvasAgentEvents.saveRun(); await refreshRuns(); return state.runId; }
  async function newRun() { if (state.busy) return; state.busy=true; window.CanvasAgentEvents.stop(); state.runId=''; state.sequence=0; clearRun(); status('正在创建会话'); try { const data=await window.CanvasAgentClient.createRun(); state.runId=data.run.id; window.CanvasAgentEvents.saveRun(); renderRun({run:data.run,messages:[],events:[],tasks:[],artifacts:[]}); await refreshRuns(); } catch (e) { system(e.message); status('创建失败'); } finally { state.busy=false; } }
  async function send() { const input=$('canvasAgentInput'), content=input.value.trim(); if (!content || state.busy) return; state.busy=true; input.value=''; message(content,'user'); try { await ensureRun(); const data=await window.CanvasAgentClient.send({content,selected_node_ids:window.CanvasAgentBridge.selectedNodeIds(),mention_node_ids:state.mentions}); renderRun(data); window.CanvasAgentEvents.start(); } catch(e) { system(e.message); status('error'); } finally { state.busy=false; } }
  async function answer(answer) { if (!answer?.trim() || !state.runId) return; try { const data=await window.CanvasAgentClient.answer(answer.trim()); if (data.plan) window.CanvasAgentPlan.render(data.plan); else status('已收到回答'); window.CanvasAgentEvents.start(); } catch(e) { system(e.message); } }
  async function confirm(approved) { if (!state.plan || !state.runId) return; try { const authorize=$('canvasAgentAuthorizeNodes')?.checked; const data=await window.CanvasAgentClient.request(`/api/canvas-agent/runs/${encodeURIComponent(state.runId)}/confirm`, {method:'POST', body:JSON.stringify({plan_version:state.plan.version,approved,authorized_node_ids:authorize ? state.mentions : []})}); renderRun(data); if (approved) window.CanvasAgentBridge.refreshCanvas(); window.CanvasAgentEvents.start(); } catch(e) { system(e.message); } }
  async function cancel() { if (!state.runId) return; try { renderRun(await window.CanvasAgentClient.cancel()); window.CanvasAgentEvents.stop(); } catch(e) { system(e.message); } }
  function addSelectedMentions() { const ids=window.CanvasAgentBridge.selectedNodeIds(); state.mentions=[...new Set([...state.mentions,...ids])]; renderMentions(); if (!ids.length) system('请先在画布上选中节点。'); }
  function init() { $('canvasAgentToggle').addEventListener('click',()=>{panel.hidden=!panel.hidden;if(!panel.hidden){refreshRuns();window.CanvasAgentEvents.recover();}}); ['pointerdown','mousedown','click','dblclick'].forEach(type=>panel.addEventListener(type,event=>event.stopPropagation())); $('canvasAgentClose').addEventListener('click',()=>panel.hidden=true); $('canvasAgentRunSelect').addEventListener('change',event=>window.CanvasAgentEvents.switchRun(event.target.value)); $('canvasAgentNewRun').addEventListener('click',newRun); $('canvasAgentSend').addEventListener('click',send); $('canvasAgentCancel').addEventListener('click',cancel); $('canvasAgentMention').addEventListener('click',addSelectedMentions); $('canvasAgentInput').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send();}}); window.addEventListener('beforeunload',window.CanvasAgentEvents.stop); renderMentions(); refreshRuns(); window.CanvasAgentEvents.recover(); }
  window.CanvasAgentPanel={init,status,message,system,renderRun,clearRun,refreshRuns,send,answer,confirm,cancel}; init();
})();
